### ISSUE TITLE
Custom Entities

### ISSUE THREAD

**Issue by eili77** [ulic75/power-flow-card#100]
Hi, 
I just discovered this visualization of energy flow and I really like it.
Besides the default entities, I think it would be great if there would be a possibility to define additional _custom_ entities. 
In order to indicate the flow of power, a parameter specifying endpoint-entities of flow such as "grid-to-_wallbox_".
Cheers
Christian

**Comment by Cameleon99** [comment]
Would add to this as I have also 'car' but also 'hot water (immersion heater)' as another main source of consumption that I would like to identify.

**Comment by arnold34740** [comment]
Hi for sure , water boiler with car intégration and the ability to change color and add percentage in a existing circle .
Thanxs father christmas . Good work anyway

**Comment by BadgerLoaf** [comment]
I think feature request #67 would cover this?
