### ISSUE TITLE
Split "Home" and "Car"

### ISSUE THREAD

**Issue by MikeEllis-personal** [ulic75/power-flow-card#101]
Whilst the Tesla App only splits out the car from the house if the car is a Tesla vehicle, other chargers (e.g. Zappi) can report all five values (grid/solar/battery/house/car) separately. It would be nice to show this with a fifth "Car" circle above/below the "Home" circle. 

As some houses may have multiple solar systems, batteries and/or electric cars, it would be even better if multiple of each of these could be specified.

This would probably address Issue #98 as well.

**Comment by Cameleon99** [comment]
Added to that, if you have a Zappi, you would likely have an Eddi (immersion heater diverter) which would also be nice to report too! That would make this card perfect for me.

**Comment by Steve-gnome** [comment]
all the above! please!

**Comment by ds20prefecture** [comment]
Agreed - You could genericise it by adding home-consumer1,2,3,... that would be "children" of home with flow and daily total values, a secondary display value and a selectable icon. Would also be nice that a click on the entity opens a particular attribute history.

**Comment by Ottmar0815** [comment]
I wan´t this also please!!!

**Comment by BadgerLoaf** [comment]
I think feature request #67 would cover this?

**Comment by ehsnils** [comment]
I would also like to have this.

**Comment by ulic75** [comment]
This currently falls outside the [scope/goal](https://github.com/ulic75/power-flow-card#goalscope) of this card.  Feel free to work it and make any changes you desire.
