### ISSUE TITLE
Grid and gas are not added

### ISSUE THREAD

**Issue by pbranly** [ulic75/power-flow-card#114]
Hi
Very interesting card .
Why don't you add grid and gas consumption when gas is entered in kWh ? This should be the same when entered in m3 in a further step using an average kWh/m3 coef.
HA development team doesn't want to do that for conception issue as they say but you could 
Thanks 
Philippe 
![image](https://user-images.githubusercontent.com/22018509/202373900-9c53f3f4-2503-4bb9-bdb1-87dd86ca1bf4.jpeg)

**Comment by ulic75** [comment]
The intention is to mirror the energy card.  There are no plans to combine gas and electricity.

**Comment by pbranly** [comment]
Thank you very much for your answer 
I understand nevertheless as in the energy panel it is a pity to have an “home” name in which we see 2 types of energy without making the addition
Phil
