### ISSUE TITLE
Two Power Flow Cards in the same dashboard

### ISSUE THREAD

**Issue by Joao-Sousa-71** [ulic75/power-flow-card#118]
Hello,

I have two power flow cards (peak and off-peak) in the same dashboard and that creates the following error in the log:
``2022-12-04 18:49:16.224 ERROR (MainThread) [frontend.js.latest.202211080] http://192.168.X.XXX:8123/frontend_latest/app.0706b45e.js:850:114174 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "power-flow-card" has already been used with this registry``
I believe that is something that should not be hard to fix.
Thanks in advance for your help.

**Comment by ulic75** [comment]
Have you checked to make sure it's not being included in your resources twice?  That is the only way I can reproduce this error.  Including the card in the UI multiple times does not cause this.

**Comment by Joao-Sousa-71** [comment]
@ulic75 yes... my bad! I had one manual resource quite old and another added by  HACS.
Thank you very much for your prompt answer and support.
