### ISSUE TITLE
The energy balance for the whole house is not good.

### ISSUE THREAD

**Issue by muffintsi** [ulic75/power-flow-card#121]
![obraz](https://user-images.githubusercontent.com/74093450/210059204-5cfe68e1-8c45-4e8e-ac56-83073e7f8661.png)

The energy balance for the whole house is not good. The amount of energy transferred to the grid is not taken into account.

grid:
   production: -109.7W
   consumption: 178.6W
solar: 592.1W (PV output from inverter)

The house (DOM) demand is 880.5W, and 592.1W + 178.6W + (-109.7W) = 661W

ERRATA:
It was a negative value problem. I resolved it by template sensor.

**Comment by ulic75** [comment]
Yeah.  All values are expected to be positive values.  Glad you got it sorted out.
