### ISSUE TITLE
async_setup_platforms issue with version 2023.3

### ISSUE THREAD

**Issue by frog60** [ulic75/power-flow-card#139]
I got this issue today after integrating GOeCharger Version 0.15.1. Mostly all entities are in status "unavailable". 

Hope the following log entry will help to solve this issue.

WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; **this will fail in version 2023.3.** Please report issue to the custom integration author for goecharger_mqtt using this method at custom_components/goecharger_mqtt/__init__.py, line 44: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by kpfleming** [comment]
`goecharger_mqtt` is not published in this repository :-)

**Comment by ulic75** [comment]
Yeah, I'm not sure this has anything to do with the Power Flow card.

**Comment by frog60** [comment]
Sorry, it seems so that I put this issue in the wrong project. Will remove it, so you can close/reject it. ;-)
