### ISSUE TITLE
Feature Request: Units Watt

### ISSUE THREAD

**Issue by Asinke** [ulic75/power-flow-card#14]
Linking your power distribution card, goes nicely next to the default Energy card.
However, I would like to see the power consumption expressed in Watts.

Can you add this?

**Comment by purcell-lab** [comment]
Event better would be to scale up and down as required.
Maybe W below a threshold (< 5000 W) and kW above (6.7 kW)

**Comment by ulic75** [comment]
Just curious. Do your entities report watts or kilowatts?

**Comment by purcell-lab** [comment]
Different for different systems. SolarEdge reports in W, powerwall reports in kW.

Energy Dashboard and tesla-style-power-card can take either input and convert.

**Comment by AviadorLP** [comment]
> Just curious. Do your entities report watts or kilowatts?

My entities report in W. From SolaX integration. Lots of systems report in W and lots of other in kW.
It would be nice if there was an option that simply adjusts the labels in your card to W.

**Comment by Asinke** [comment]
Using templates I can have entities report whatever metric as is needed. The gui in the current version however is stuck to kW

Sent from my iPhone

On 9 May 2022, at 02:54, AviadorLP ***@***.***> wrote:

﻿

Just curious. Do your entities report watts or kilowatts?

My entities report in W. From SolaX integration. Lots of systems report in W and lots of other in kW.
It would be nice if there was an option that simply adjusts the labels in your card to W.

**Comment by joostvkempen** [comment]
My entities report in W. Using templates I could change them to kW, so I can use them with this card. However prefer them to use with W, because it's more accurate when showing realtime production and consumption. The card I'm using now (https://github.com/gurbyz/power-wheel-card) supports both, with the constraint that all entities used should have the same unit of measurement.

**Comment by justdeepred** [comment]
Yes please add W, all of my sensors shows values in Watts, I know it's doable via template but would be lovely to be able to easily switch from kW to W and vice versa

**Comment by medivb** [comment]
My entities also report in W by default... This would be highly appreciated. Very nice card!

**Comment by jesserockz** [comment]
The original card, https://github.com/reptilex/tesla-style-solar-power-card/ (where Home Assistant "copied" from) has W / kW auto detection and configuration. Maybe look at that card source on how to implement it.

**Comment by AviadorLP** [comment]
Downloaded v.2.1.0 from hacs restarted HA inserted watt_threshold: 5000
But still same thing shows watts but with KW label as before.
cannot see anything different.

Here is an example of one of my sensors
```

template:
- sensor:
  - name: SolaX Electric Meter
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    icon: mdi:transmission-tower
    state: "{{ 0 - states('sensor.solax_measured_power')|int(default=0) }}"
```

What am i doing wrong ?

**Comment by ulic75** [comment]
The display of watts or kilowatts is a configuration option. That way people can use which ever they want regardless of their sensors. You can find it in the readme.

**Comment by AviadorLP** [comment]
> The display of watts or kilowatts is a configuration option. That way people can use which ever they want regardless of their sensors. You can find it in the readme.

That's what i did, that is why i inserted 
watt_threshold: 5000
nothing happened....

**Comment by medivb** [comment]
Great work, thanks!
