### ISSUE TITLE
Unable to set W instead of kW

### ISSUE THREAD

**Issue by budisek** [ulic75/power-flow-card#155]
All my entities are measured in Watts but it shows kiloWatts only even when i set the treshold. What am I doing wrong? 
![IMG_2988](https://user-images.githubusercontent.com/35574450/229331845-9c361da5-7031-4e32-89cc-b69b9bde1145.png)

**Comment by Snux** [comment]
You have a typo.... should be watt_threshold not watt_treshold

**Comment by budisek** [comment]
ou my fault... Thanks a lot.
