### ISSUE TITLE
Dont work since HA 2023.4.x?

### ISSUE THREAD

**Issue by dfarin** [ulic75/power-flow-card#156]
Hiho, since i update to 2023.4.x power-flow-card doesnt work anymore.
Are here any changes i miss ?
Dashboard: Custom element doesnt exist
console:
Uncaught (in promise) http://homeassistant.local:8123/local/power-flow-card/power-flow-card.js
power-flow-card.js?hacstag=484538222262:69 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at yt.render (power-flow-card.js?hacstag=484538222262:69:2873)
    at yt.update (power-flow-card.js?hacstag=484538222262:23:410)
    at yt.performUpdate (power-flow-card.js?hacstag=484538222262:11:5057)
    at yt.scheduleUpdate (power-flow-card.js?hacstag=484538222262:11:4704)
    at yt._$E_ (power-flow-card.js?hacstag=484538222262:11:4612)

**Comment by ulic75** [comment]
I've tried it with 2023.4.0 and 2023.4.2 and it works without issue.  Looks like it's erroring trying to read the state of an entity.  Maybe one of your entities broke with 2023.4.x?

**Comment by dfarin** [comment]
> I've tried it with 2023.4.0 and 2023.4.2 and it works without issue. Looks like it's erroring trying to read the state of an entity. Maybe one of your entities broke with 2023.4.x?

Thanks a lot, yes, you are right, my gas entity is broken , just need to comment it out and flow card works again. :)
