### ISSUE TITLE
Card is not showing since Home Assistant 2023.4.3

### ISSUE THREAD

**Issue by kai-seipp** [ulic75/power-flow-card#161]
Hi,

Since I updated to home assistant 2023.4.3 my power flow card is not showing anymore on my dashboards. I did not do any changes on its configuration. 

I did try it on different browser, within the iOS App and on different devices (phone, iPad, mac). Reload of browser and restarting home assistant did not bring any change.

**Comment by ulic75** [comment]
I'm running 2023.4.4 without issue. I'm pretty sure it worked with .3 also. It's possible one of you entities is broken and not returning state.

**Comment by kai-seipp** [comment]
Thanks for the feedback! 
You are right. One of the entities did go bad.
