### ISSUE TITLE
Feature Request - Display changes during grid failure

### ISSUE THREAD

**Issue by js1804** [ulic75/power-flow-card#166]
Hi
Can you perhaps add functionality to:
*Color the grid circle a custom color during grid failure
*Change the solid line from grid to battery/home load to dotted (or custom) during grid failure (or hide?)

Also, what environment do you compile/build your code in. I tried within Windows with application Visual Studio Code but ran into alot of issues.

Thanks in advance.
![Home Assistant — Mozilla Firefox](https://github.com/ulic75/power-flow-card/assets/129187450/fb3770c5-2962-4791-896e-0b6a0adba1c9)

**Comment by ulic75** [comment]
Very interesting ideas, but they are currently outside the scope of the features provided.

I developed it on a mac, can't imagine why it wouldn't work on Windows.  If you want to open a [discussion](https://github.com/ulic75/power-flow-card/discussions) with the errors you're seeing I'll see if I can help.
