### ISSUE TITLE
![powerflow](https://github.com/ulic75/power-flow-card/assets/77579632/07650fc7-714b-4b79-b98c-7b6752dff4d8)

### ISSUE THREAD

**Issue by titizb33** [ulic75/power-flow-card#168]
![powerflow](https://github.com/ulic75/power-flow-card/assets/77579632/07650fc7-714b-4b79-b98c-7b6752dff4d8)

Hi,
Good morning,
At home the battery charge is not deducted from the consumption of my house.
I don't understand the behavior of the battery bubbl

1100 - 14 - 249 = 837 <> 1100

type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.shellyplus1pm_90380c37bd4c_switch_0_power
    state_of_charge: ''
    invert_state: true
    icon: mdi:storage-tank
    name: ECS
    display_state: one_way
  grid:
    entity: sensor.shellyem_b9ed49_channel_1_power
    display_state: one_way
  solar:
    entity: sensor.est_power
  individual1:
    entity: sensor.shellyem_b9ed49_channel_2_power
    name: Clim
    icon: mdi:air-conditioner
  individual2:
    entity: sensor.piscine_power
    name: Piscine
    icon: mdi:pool
  home: {}
clickable_entities: true
display_zero_lines: false
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000

_Originally posted by @titizb33 in https://github.com/ulic75/power-flow-card/discussions/163#discussioncomment-6050517_

**Comment by ulic75** [comment]
As mentioned previously.  You are using the `power-flow-card-plus` card.  This card is `power-flow-card`.  Please report you issues in that repository.
