### ISSUE TITLE
Lost UI editor?

### ISSUE THREAD

**Issue by Lips2000** [ulic75/power-flow-card#171]
Once everything settled down a bit, seems ok.

Still missing UI editor though. :(

Mark

**Comment by Lips2000** [comment]
Was running with beta and update to latest by accident.

Lost UI config and flow lines are now way too choppy (stuttering) and, for the first time, I have my Grid charging batteries...what?

Tried to rollback to beta but not listed.

Ooops.

Mark

**Comment by Lips2000** [comment]
Not sure how to explain the math on this one:

<img width="372" alt="Screenshot 2023-07-10 at 8 29 02 AM" src="https://github.com/ulic75/power-flow-card/assets/136117577/3063e375-53f1-4a89-b6c2-b192bf5489d5">

**Comment by Lips2000** [comment]
I did notice this:

<img width="481" alt="Screenshot 2023-07-10 at 8 48 25 AM" src="https://github.com/ulic75/power-flow-card/assets/136117577/cbfb5265-8bcd-4b32-9123-581c2ada6b35">

**Comment by ulic75** [comment]
You might be looking for a different card of a similar name.  This card has never had a GUI configuration option.

**Comment by Lips2000** [comment]
You are correct. 

I realized my error too late. Thank you for the reply.
