### ISSUE TITLE
Allow single Grid consumption entity to be inverted

### ISSUE THREAD

**Issue by jesserockz** [ulic75/power-flow-card#21]
My Grid consumption entity from my inverter is positive for export and negative for import. 
It would be great to allow configuring this via the card instead of having to create a template sensor.

**Comment by AviadorLP** [comment]
Yes it would be useful, for the battery also. had to invert both sensors.
And some people don't know how to create templates

**Comment by jesserockz** [comment]
Thanks @ulic75
