### ISSUE TITLE
Flow dots still appearing when 0 kW is displayed

### ISSUE THREAD

**Issue by ulic75** [ulic75/power-flow-card#28]
After adding support for watts, small values of kW (0.033 for example) are displayed as 0 kW, but are still showing a flow dot since everything is calculated using watts as a baseline.  That doesn't work.  I'll have to find a different way to implement watts and kilowatts.

**Comment by AviadorLP** [comment]
Maybe use kW with two decimals. Then flow dots will make sense!

**Comment by ulic75** [comment]
Not exactly fixed in #32, but it satisfies my needs.
