### ISSUE TITLE
Missing FLows - Battery 2 Grid and Grid 2 battery ?

### ISSUE THREAD

**Issue by AviadorLP** [ulic75/power-flow-card#29]
Don't know if your chart should show this flows or not but i got this today.

![image](https://user-images.githubusercontent.com/93188698/167731295-2ede77e3-997e-43e1-af2a-8446ff67cd3c.png)

Missing 4W from Battery to Grid...

The flows in the other chart are completely calculated in a yaml script of my own making.
Also that -55W that's an estimated inverter consumption power that is being consumed at the time that i also calculated.
If you need help, ill do what i can !

**Comment by ulic75** [comment]
Your battery sends power to the grid?  That seems strange to me, but okay.  Does your battery also charge from the grid?

**Comment by AviadorLP** [comment]
Well all batteries can charge from the grid, very useful when there is an overcast forecast for next day with minimum or no sun. i charge the with cheap electricity and let it go to the house during the day when the electricity become more expensive (i have cheaper electricity from 2200 till 0800 am)

**Comment by AviadorLP** [comment]
i don't send electricity to the grid myself. But there are those that do, i believe It  involves a contract selling electricity and they receive higher prices at specific hours so they send the battery power at those hours.
But in some cases you need to force a battery discharge an there in no other way other then send to grid....

Now at the example shown above, since inverters are not that fast to react and we take instant sensor readings the inverter at that time did not have time yet to adjust power transfers (i think it takes a few tens of seconds like 0.1s or 0,3s not sure about this and there are inverter faster than others). **So at that time the battery is sending more energy than the house is demanding the rest is going to the grid for the moment** till the inverter corrects this moments later.

**Comment by AviadorLP** [comment]
if it helps here is the formula i use to calculate the flows from grid2batt and batt2grid in yaml
If you want to implement this....


```
# Required to reduce code later on
  - name: APF Grid Import
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    state: >
      {% if states('sensor.apf_grid_entity')|int(default=0) < 0 %}
        {{ states('sensor.apf_grid_entity')|int(default=0)|abs }}
      {% else %}
        0
      {% endif %}

  - name: APF Grid2Batt
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    state: >
      {% if states('sensor.apf_grid_import')|int(default=0) > states('sensor.apf_real_house_load')|int(default=0) %}
        {{ states('sensor.apf_grid_import')|int(default=0) - states('sensor.apf_real_house_load')|int(default=0) }}
      {% else %}
        0
      {% endif %}

  - name: APF Batt2Grid
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    state: >
      {% if states('sensor.apf_battery_entity')|int(default=0) < 0 %}
        {% if states('sensor.apf_battery_entity')|int(default=0)|abs > states('sensor.apf_real_house_load')|int(default=0) %}
          {{ states('sensor.apf_battery_entity')|int(default=0)|abs - states('sensor.apf_real_house_load')|int(default=0) }}
        {% else %}
          0
        {% endif %}
      {% else %}
        0
      {% endif %}

```

Hope it makes sense to you...
