### ISSUE TITLE
Solar text color

### ISSUE THREAD

**Issue by flixlix** [ulic75/power-flow-card#35]
I noticed a difference between the "Power Flow Card" and the core "Energy Flow Card".
The text of the solar production is black on the original "Energy Card" and orange on the power Flow card.
![image](https://user-images.githubusercontent.com/61006057/168080561-a81bce57-8c51-4b84-aa8c-4d133e3aa4f6.png)
![image](https://user-images.githubusercontent.com/61006057/168080635-9fa4651e-8326-4e78-b47d-dfa9b230b26b.png)

**Comment by ulic75** [comment]
In almost all aspects my goal was to mirror the official energy distribution card.  However in this case it was an intentional design decision. I feel like it's more consistent with the other bubbles/circles.  If you can't stand it I suppose it could be made themable.

**Comment by flixlix** [comment]
I have thought about this and I don't think I agree with your decision.
In the examples of the grid and the battery, the color of the text describes the "throughput" of the line that has that color.
For example: In the battery discharging, the green text describes the green line.
In the case of solar though, the text being orange, would mean, only the solar power going into the house, which isn't the case, since the solar can also charge the battery or export to the grid.

**Comment by flixlix** [comment]
For anyone interested, I [forked](https://github.com/flixlix/power-flow-card) this repo with the same text color as the Energy Flow Card

**Comment by ulic75** [comment]
:tada: This issue is resolved in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/ulic75/power-flow-card/releases/tag/v2.6.0)
