### ISSUE TITLE
Make the number of decimal digits contextual

### ISSUE THREAD

**Issue by Ndrinta** [ulic75/power-flow-card#45]
Hi, fist of all, great job @ulic75!

Second of all, I've noticed that the setting for `kw_decimal` is used also when the figure is below the `watt_threshold` and simple Watts are displayed.
I'd be great if we could have a similar parameter when in the 'below-threshold' region, too. Maybe, simply `w_decimal`.

A further upgrade would be to be able to specify the unit of measure (I'd kinda like to have at least the option to use it to display energy (kWh/Wh) instead of instantaneous power). I know this would be a 'different use' for this card, but flexibility is always a plus IMHO).

**Comment by Ndrinta** [comment]
Oh, correction. Actually no, `kw_decimal` not _used_ in the 'below-threshold' region.
```
  private displayValue = (value: number) =>
    value >= this._config!.watt_threshold
      ? `${round(value / 1000, this._config!.kw_decimals)} kW`
      : `${round(value, 1)} W`;
```
It always rounds it up to the first decimal. I haven't noticed because I have `kw_decimal` set equal to `1`, too.
Anyways, same issue, not customizable so no good.
Looks like a super easy fix, I'll make a pull request tomorrow; but only if there isn't friction by anyone, of course. :)

**Comment by Ndrinta** [comment]
Oh, correction. Actually no, `kw_decimal` is _not used_ in the 'below-threshold' region.
```
  private displayValue = (value: number) =>
    value >= this._config!.watt_threshold
      ? `${round(value / 1000, this._config!.kw_decimals)} kW`
      : `${round(value, 1)} W`;
```
It always rounds it up to the first decimal. I haven't noticed it because I also have `kw_decimal` set equal to `1`.
Anyways, same issue, not customizable so no good.
Looks like a super easy fix, I'll make a pull request tomorrow; but only if there isn't friction by anyone, of course. :)

**Comment by Ndrinta** [comment]
I don't like to see _edited_ on my comments. Just regular OCD.

I have enough resolution to monitor decimals of Watts, I don't wanna see them on the card, though.

Yep, but not as a card in the regular Lovelace (anyways, secondary).

**Comment by ulic75** [comment]
https://www.home-assistant.io/dashboards/energy/ They aren't available via the card picker, but you can use them on any dashboard you'd like.  I've made my own custom dashboard that includes many of these, plus power-flow-card.

**Comment by Ndrinta** [comment]
I completely missed this, the more you know...

**Comment by ulic75** [comment]
I'm not sure why you closed your PRs.  Anyhow, I've included the option.  Thanks again for your contribution.
