### ISSUE TITLE
Feature Request: Title Text

### ISSUE THREAD

**Issue by lloydbayley** [ulic75/power-flow-card#70]
FANTASTIC little card. Thank you so much for your efforts.

May I request an optional title text/name field at the top of the card.
The reason is, by example, I have multiple 12v batteries in a little solar project and would like to identify them easily.
Might be useful for people with more than one power source in a project.

**Comment by ulic75** [comment]
Do you mean for the whole card?

Try adding `title: Custom Flow Title` to you config.  I should probably document that.

**Comment by lloydbayley** [comment]
Oh you're a bloody star! That's great!
I thought it a little odd it had no title but I figured it would usually be for a big house system and not many.
Turns out it was an undocumented feature! :)

Thanks again!
