### ISSUE TITLE
Feature Request - Scale

### ISSUE THREAD

**Issue by nukemrules** [ulic75/power-flow-card#76]
First of all, what a great card you've made.

The reason I'm requesting scale as an option is that I would like to use this card on a dashboard and maybe there are others interested.
In my case it runs specifically on a Google Nest Hub. This has a relative small screen but it is perfect for an overview for what is happening in my home. Unfortunately, when using this card the text (values and sources) and icons are just to darn small to read when your just a meter (3 feet) away from the screen.

Would it be possible to add something like a scale option to enlarge everything?

**Comment by ulic75** [comment]
This card was built from the source of the Energy Distribution card.  Does it too have an unsatisfactory display on your Nest Hub?

**Comment by nukemrules** [comment]
It has the same exact issue, that is why I searched for something different.

**Comment by barthoefs** [comment]
I want this! Would be great if there was a scaling option (like x1.5/x2/x3...). I can't read it on my nest hub...

**Comment by ulic75** [comment]
This currently falls outside the [scope/goal](https://github.com/ulic75/power-flow-card#goalscope) of this card.  Feel free to work it and make any changes you desire.
