### ISSUE TITLE
An option to show battery charge with available energy (instead of, or perhaps in addition to, percentage)

### ISSUE THREAD

**Issue by brodykenrick** [ulic75/power-flow-card#78]
Hi,

 I love this card. It brings consistency my power and energy dashboards. Thank you.

 I would like the amount of charge in the battery to reflect available energy rather than a percentage.

 I think percentage is obviously useful -- it is certainly good to know when the battery is full.

However, as my battery (powerwall) has a reserve level I would prefer to know how much energy is available until I hit reserve (and therefore will start drawing from the grid). My reserve is set to 15% (it is 20% by default).

![image](https://user-images.githubusercontent.com/5006130/174475786-ad004288-ac5a-4923-ac3c-7831801d55c3.png)

I don't think there is enough space inside the battery circle to have both a percentage and an "available energy" displayed at teh same time.

I think the visual indicator of the level of the battery on the icon is probably sufficient for the batteries reaching capacity.

So I think that using the available energy from a sensor for the displayed value and the battery charge percentage for the icon is probably the best tradeoff/layout.

**Comment by ulic75** [comment]
There is a related request in #68, I'll close this in favor of that one.

**Comment by ulic75** [comment]
@brodykenrick Out of curiosity, what is the entity name for that?  The powerwall setup I use for my production testing doesn't seem to have that entity.
