### ISSUE TITLE
Custom element doesn't exist: power-flow-card

### ISSUE THREAD

**Issue by kmb36td** [ulic75/power-flow-card#81]
Followed the install instructions..
Home Assistant Core 2022.6.7

installed through HACS
added custom card.....
Custom element doesn't exist: power-flow-card.
type: custom:power-flow-card

tried Manual install..
Integration error: resources - Integration 'resources' not found.

i see it installed in www\community
I see the card update entity but how do I add the card..

**Comment by kmb36td** [comment]
I dont know what I did but I see the card now at the bottom after a few hours.. it works now..

**Comment by blundell** [comment]
Cache issue, fix mentioned in #96
