### ISSUE TITLE
Dots jumping on Safari based UIs

### ISSUE THREAD

**Issue by SparkyDan555** [ulic75/power-flow-card#82]
My entities update every second and when they do, the dots traversing the lines jump positions. They don't flow smoothly along the lines. To make matters worse, the entity for solar production doesn't always update at the same time as the entity for grid import/export so the dots jump around ver half a second or so. I think a fix needs to be implemented so the speed of the dots changes when the entities change in real-time, not just by calculating the time to travel along the line at the start of its path. i.e. if the power increases midway through the dot's travel, it speeds up right there and then.

**Comment by ulic75** [comment]
This functionality should exist already as it was an initial issue I had to overcome when designing the card.  I'd have to build some kind of custom setup to try to update multiple values every 0.5-1s to try to simulate what you describe.

**Comment by SparkyDan555** [comment]
See the following screen recording as an example. When the values update, the dots kind of glitch and don't flow smoothly:

https://user-images.githubusercontent.com/38540799/177394989-e9a99241-8f63-40aa-bea3-d4c6391ae759.mov

**Comment by ulic75** [comment]
Have you tried other browsers?  Can you provide me your browser specifics?

**Comment by SparkyDan555** [comment]
Just tried it in Chrome and it works okay. It seems to glitch in the Home Assistant companion app (2022.358) on iPhone, in Safari 15.5 on Mac and the companion app on Mac.

**Comment by ulic75** [comment]
I was able to reproduce it in Safari.  So at least I have something to test against.

**Comment by ulic75** [comment]
Could be a little janky still, but should be an improvement.

**Comment by emign** [comment]
Hi. I use v 2.5.1 and I encounter the same problem. Its not as bad as the recording above but still noticeable. Especially if you use an iPad as Home dashboard. Can we maybe add a setting, which lets the card only update every x seconds?

https://user-images.githubusercontent.com/5278352/191817007-bfd1e555-13ff-4a18-83fa-f50cbaeaddb1.mov
