### ISSUE TITLE
Custom element doesn't exist: power-flow-card

### ISSUE THREAD

**Issue by slyglif** [ulic75/power-flow-card#96]
I'm not sure if this is something I'm doing wrong, or if something changed in the latest HA release, but when I try to add the card to a dashboard I get the error "Custom element doesn't exist: power-flow-card".  I have added it to the resources.  For reference, I did add and get the content-card-example working using the same procedure.

I'm running HA 2022.7.7 / 20220707.1 from the official container image.

**Comment by ulic75** [comment]
I'm not having any issues with 2022.7.7.  I'd guess that it's no loading correctly.  I don't know if you know how to look at network calls in your browser, but I would guess that it's not getting loaded correctly because of a typo or something like that.

**Comment by slyglif** [comment]
I don't think it's a typo, as I see "power-flow-card.js" in the Sources section of Develop view in Safari.  I do see the following error int he Console section: "[Error] Unhandled Promise Rejection: "https://<HOSTNAME>:8123/local/power-flow-card.js"

**Comment by slyglif** [comment]
OK, not sure what it was, but recreating the container and restarting Safari seems to have fixed it.  Sorry for the noise!

Also, ty for this card, it is actually what I was looking for!

**Comment by blundell** [comment]
Had the same problem in chrome. Doing a "empty cache + hard reload" fixed it 👍
