### ISSUE TITLE
Battery icon - replace with car

### ISSUE THREAD

**Issue by kongjudas** [ulic75/power-flow-card#98]
I know this is way out of line and the purpose of this card, but I use the car charger as "battery". I don't understand the path code for the full battery icon in power-flow-card.js, but maybe you could just tell me what to replace to have mdi:car-electric instead of mdi:battery?

I understand if you don't bother, too :) 

**Feature request:** Add car charger to the card, like the Tesla Power Card.

**Comment by BadgerLoaf** [comment]
I think feature request #67 might cover this?

**Comment by ulic75** [comment]
This currently falls outside the [scope/goal](https://github.com/ulic75/power-flow-card#goalscope) of this card.  Feel free to work it and make any changes you desire.
